// Regenerates src/data/ofac-sdn.ts from the official OFAC SDN list.
//
//   npx tsx scripts/update-ofac.ts            # download from treasury (≈30 MB XML)
//   npx tsx scripts/update-ofac.ts SDN.XML    # use a local copy
//
// Only "Digital Currency Address - <TICKER>" identifiers are extracted. The
// generated file is deterministic (sorted) so diffs show exactly what OFAC changed.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/SDN.XML";
const OUT = new URL("../src/data/ofac-sdn.ts", import.meta.url);

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .trim();
}

function tag(block: string, name: string): string | null {
  const m = block.match(new RegExp(`<${name}>([\\s\\S]*?)</${name}>`));
  return m?.[1] !== undefined ? decodeEntities(m[1]) : null;
}

export function normalizeListedAddress(raw: string): string {
  const a = raw.trim();
  return /^0x[0-9a-fA-F]{40}$/.test(a) ? a.toLowerCase() : a;
}

async function loadXml(): Promise<string> {
  const local = process.argv[2];
  if (local) return readFileSync(local, "utf8");
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`OFAC download failed: HTTP ${res.status}`);
  return await res.text();
}

async function main(): Promise<void> {
  const xml = await loadXml();
  const publish = xml.match(/<Publish_Date>(\d{2})\/(\d{2})\/(\d{4})<\/Publish_Date>/);
  if (!publish) throw new Error("Publish_Date not found — not an SDN.XML export?");
  const publishDate = `${publish[3]}-${publish[1]}-${publish[2]}`;
  const recordCount = Number(tag(xml, "Record_Count") ?? "0");

  const rows = new Map<string, [string, string, number, string]>();
  for (const m of xml.matchAll(/<sdnEntry>([\s\S]*?)<\/sdnEntry>/g)) {
    const block = m[1] as string;
    const uid = Number(tag(block, "uid"));
    const name = [tag(block, "firstName"), tag(block, "lastName")].filter(Boolean).join(" ");
    for (const id of block.matchAll(/<idType>Digital Currency Address - ([A-Za-z0-9]+)<\/idType>\s*<idNumber>([^<]+)<\/idNumber>/g)) {
      const ticker = id[1] as string;
      const address = normalizeListedAddress(decodeEntities(id[2] as string));
      const key = `${address}|${ticker}`;
      if (!rows.has(key)) rows.set(key, [address, ticker, uid, name]);
    }
  }
  if (rows.size < 100) throw new Error(`only ${rows.size} digital currency addresses parsed — format changed?`);
  const sorted = [...rows.values()].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : a[1] < b[1] ? -1 : 1));
  const sha256 = createHash("sha256").update(xml).digest("hex");
  const byTicker: Record<string, number> = {};
  for (const r of sorted) byTicker[r[1]] = (byTicker[r[1]] ?? 0) + 1;

  const body = [
    "// GENERATED by scripts/update-ofac.ts from the official OFAC SDN list — do not edit by hand.",
    `// Source: ${SOURCE}`,
    "// Each row: [normalized address (EVM lowercased), OFAC ticker, SDN entry uid, SDN entry name].",
    `export const OFAC_SDN_META = ${JSON.stringify({ source: SOURCE, publish_date: publishDate, record_count: recordCount, addresses: sorted.length, by_ticker: byTicker, sha256 })} as const;`,
    "",
    "export const OFAC_SDN_ADDRESSES: ReadonlyArray<readonly [string, string, number, string]> = [",
    ...sorted.map((r) => `  ${JSON.stringify(r)},`),
    "];",
    "",
  ].join("\n");
  writeFileSync(OUT, body);
  console.log(`OFAC SDN ${publishDate}: ${sorted.length} digital currency addresses from ${recordCount} records → ${OUT.pathname}`);
  console.log(JSON.stringify(byTicker));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
