// Rebuilds the community threat feeds used by the provider.
//
//   npx tsx scripts/update-threat-feeds.ts                 # MetaMask list → src/data (embedded, committed)
//   npx tsx scripts/update-threat-feeds.ts --scamsniffer   # + ScamSniffer → .cache/threat-feeds (never committed)
//   npx tsx scripts/update-threat-feeds.ts --scamsniffer --upload   # + upload ScamSniffer blobs to the Worker KV
//
// Licensing: MetaMask eth-phishing-detect is DBAD-1.2 (derived work with attribution,
// see THIRD_PARTY_NOTICES.md). ScamSniffer scam-database is GPL-3.0, so its derived
// blobs are only stored in the operator's KV and read at runtime; they are never
// committed to this MIT repository or bundled into the Worker.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { buildHashBlob, feedHost } from "../src/threat-intel.js";

const MM_REPO = "MetaMask/eth-phishing-detect";
const MM_URL = `https://raw.githubusercontent.com/${MM_REPO}/main/src/config.json`;
const SS_REPO = "scamsniffer/scam-database";
const SS_DOMAINS = `https://raw.githubusercontent.com/${SS_REPO}/main/blacklist/domains.json`;
const SS_ADDRESSES = `https://raw.githubusercontent.com/${SS_REPO}/main/blacklist/address.json`;
const DATA = new URL("../src/data/", import.meta.url);
const CACHE = new URL("../.cache/threat-feeds/", import.meta.url);
export const KV_KEYS = { domains: "feed:scamsniffer:domains:v1", addresses: "feed:scamsniffer:addresses:v1", meta: "feed:scamsniffer:meta:v1" };

async function getJson<T>(url: string): Promise<{ body: T; sha256: string }> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const text = await res.text();
  return { body: JSON.parse(text) as T, sha256: createHash("sha256").update(text).digest("hex") };
}

async function headCommit(repo: string): Promise<{ sha: string; date: string }> {
  const res = await fetch(`https://api.github.com/repos/${repo}/commits/main`, { headers: { Accept: "application/vnd.github+json" } });
  if (!res.ok) throw new Error(`${repo} commit lookup: HTTP ${res.status}`);
  const c = (await res.json()) as { sha: string; commit: { committer: { date: string } } };
  return { sha: c.sha, date: c.commit.committer.date.slice(0, 10) };
}

/** Normalizes a feed entry to a host (punycode, lowercase, no www.); null for paths/invalid. */
export function normalizeFeedDomain(entry: string): string | null {
  const e = entry.trim();
  if (!e || e.includes("/") || /\s/.test(e)) return null;
  try {
    const host = new URL(`https://${e}`).hostname;
    return host && host.includes(".") ? feedHost(host) : null;
  } catch {
    return null;
  }
}

async function metamask(): Promise<void> {
  const [{ body, sha256 }, commit] = await Promise.all([
    getJson<{ blacklist?: string[]; whitelist?: string[]; fuzzylist?: string[] }>(MM_URL),
    headCommit(MM_REPO),
  ]);
  const black = (body.blacklist ?? []).map(normalizeFeedDomain);
  const hosts = black.filter((h): h is string => h !== null);
  const skipped = black.length - hosts.length;
  const allow = [...new Set((body.whitelist ?? []).map(normalizeFeedDomain).filter((h): h is string => h !== null))].sort();
  const blob = buildHashBlob(hosts);
  if (blob.byteLength / 8 < 10_000) throw new Error(`only ${blob.byteLength / 8} MetaMask entries — format changed?`);
  writeFileSync(new URL("metamask-phishing.bin", DATA), blob);
  const meta = {
    source: `https://github.com/${MM_REPO}`,
    license: "DBAD-1.2 (derived hash set, attributed in THIRD_PARTY_NOTICES.md)",
    commit: commit.sha,
    as_of: commit.date,
    entries: blob.byteLength / 8,
    skipped_path_or_invalid: skipped,
    config_sha256: sha256,
  };
  writeFileSync(
    new URL("threat-feeds.ts", DATA),
    [
      "// GENERATED by scripts/update-threat-feeds.ts — do not edit by hand.",
      "// MetaMask eth-phishing-detect blacklist, stored as sorted SHA-256 prefixes in metamask-phishing.bin.",
      `export const METAMASK_FEED_META = ${JSON.stringify(meta)} as const;`,
      "",
      "/** Hosts MetaMask's own list allowlists (feed-normalized). */",
      `export const METAMASK_ALLOWLIST: readonly string[] = ${JSON.stringify(allow)};`,
      "",
    ].join("\n"),
  );
  console.log(`MetaMask ${commit.date} (${commit.sha.slice(0, 7)}): ${meta.entries} hosts, ${allow.length} allowlisted, ${skipped} path/invalid skipped`);
}

async function scamsniffer(upload: boolean): Promise<void> {
  const [domains, addresses, commit] = await Promise.all([getJson<string[]>(SS_DOMAINS), getJson<string[]>(SS_ADDRESSES), headCommit(SS_REPO)]);
  const hosts = domains.body.map(normalizeFeedDomain).filter((h): h is string => h !== null);
  const evm = addresses.body.map((a) => String(a).trim()).filter((a) => /^0x[0-9a-fA-F]{40}$/.test(a)).map((a) => a.toLowerCase());
  mkdirSync(CACHE, { recursive: true });
  const dBlob = buildHashBlob(hosts);
  const aBlob = buildHashBlob(evm);
  writeFileSync(new URL("scamsniffer-domains.bin", CACHE), dBlob);
  writeFileSync(new URL("scamsniffer-addresses.bin", CACHE), aBlob);
  const meta = { source: `https://github.com/${SS_REPO}`, license: "GPL-3.0 (runtime use only; not distributed)", commit: commit.sha, as_of: commit.date, domains: dBlob.byteLength / 8, addresses: aBlob.byteLength / 8, note: "public data is published with a 7-day delay" };
  writeFileSync(new URL("scamsniffer-meta.json", CACHE), JSON.stringify(meta));
  console.log(`ScamSniffer ${commit.date} (${commit.sha.slice(0, 7)}): ${meta.domains} hosts, ${meta.addresses} EVM addresses → ${CACHE.pathname}`);
  if (!upload) return;
  const put = (key: string, file: URL): void => {
    execFileSync("npx", ["wrangler", "kv", "key", "put", key, "--path", file.pathname, "--binding", "RATE", "--remote", "--config", "deploy/wrangler.toml"], { stdio: "inherit" });
  };
  put(KV_KEYS.domains, new URL("scamsniffer-domains.bin", CACHE));
  put(KV_KEYS.addresses, new URL("scamsniffer-addresses.bin", CACHE));
  put(KV_KEYS.meta, new URL("scamsniffer-meta.json", CACHE));
  console.log("uploaded ScamSniffer blobs to KV (binding RATE)");
}

async function main(): Promise<void> {
  await metamask();
  if (process.argv.includes("--scamsniffer")) await scamsniffer(process.argv.includes("--upload"));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
