// Regenerates src/data/ofac-sdn.ts from the official OFAC SDN list.
//
//   npx tsx scripts/update-ofac.ts            # download from treasury (≈30 MB XML)
//   npx tsx scripts/update-ofac.ts SDN.XML    # use a local copy
//
// Only "Digital Currency Address - <TICKER>" identifiers are extracted. The
// generated file is deterministic (sorted) so diffs show exactly what OFAC changed.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

export const SOURCE = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/SDN.XML";
export const OFAC_MODULE = new URL("../src/data/ofac-sdn.ts", import.meta.url);

export type OfacRow = [string, string, number, string];
export type OfacMeta = { source: string; publish_date: string; record_count: number; addresses: number; by_ticker: Record<string, number>; sha256: string };

/** src/data/ofac-sdn.ts for a snapshot: the one format both this script and scripts/sync-embedded-feeds.ts write. */
export function renderOfacModule(meta: OfacMeta, rows: readonly OfacRow[]): string {
  return [
    "// GENERATED by scripts/update-ofac.ts from the official OFAC SDN list — do not edit by hand.",
    `// Source: ${meta.source}`,
    "// Each row: [normalized address (EVM lowercased), OFAC ticker, SDN entry uid, SDN entry name].",
    `export const OFAC_SDN_META = ${JSON.stringify({ source: meta.source, publish_date: meta.publish_date, record_count: meta.record_count, addresses: meta.addresses, by_ticker: meta.by_ticker, sha256: meta.sha256 })} as const;`,
    "",
    "export const OFAC_SDN_ADDRESSES: ReadonlyArray<readonly [string, string, number, string]> = [",
    ...rows.map((r) => `  ${JSON.stringify(r)},`),
    "];",
    "",
  ].join("\n");
}

function decodeEntities(s: string): string {
  // &amp; last: "&amp;lt;" is the text "&lt;", never "<".
  return s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&")
    .trim();
}

function tag(block: string, name: string): string | null {
  const m = block.match(new RegExp(`<${name}>([\\s\\S]*?)</${name}>`));
  return m?.[1] !== undefined ? decodeEntities(m[1]) : null;
}

export function normalizeListedAddress(raw: string): string {
  const a = raw.trim();
  return /^0x[0-9a-fA-F]{40}$/.test(a) ? a.toLowerCase() : a;
}

/** The SDN.XML bytes exactly as OFAC serves them: the signed digest is their SHA-256, so anyone can recompute it. */
async function loadXml(): Promise<Uint8Array> {
  const local = process.argv[2];
  if (local) return readFileSync(local);
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`OFAC download failed: HTTP ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

async function main(): Promise<void> {
  const bytes = await loadXml();
  const xml = new TextDecoder().decode(bytes);
  const publish = xml.match(/<Publish_Date>(\d{2})\/(\d{2})\/(\d{4})<\/Publish_Date>/);
  if (!publish) throw new Error("Publish_Date not found — not an SDN.XML export?");
  const publishDate = `${publish[3]}-${publish[1]}-${publish[2]}`;
  const recordCount = Number(tag(xml, "Record_Count") ?? "0");

  const rows = new Map<string, [string, string, number, string]>();
  for (const m of xml.matchAll(/<sdnEntry>([\s\S]*?)<\/sdnEntry>/g)) {
    const block = m[1] as string;
    const uid = Number(tag(block, "uid"));
    const name = [tag(block, "firstName"), tag(block, "lastName")].filter(Boolean).join(" ");
    for (const id of block.matchAll(/<idType>Digital Currency Address - ([A-Za-z0-9]+)<\/idType>\s*<idNumber>([^<]+)<\/idNumber>/g)) {
      const ticker = id[1] as string;
      const address = normalizeListedAddress(decodeEntities(id[2] as string));
      const key = `${address}|${ticker}`;
      if (!rows.has(key)) rows.set(key, [address, ticker, uid, name]);
    }
  }
  if (rows.size < 100) throw new Error(`only ${rows.size} digital currency addresses parsed — format changed?`);
  const sorted = [...rows.values()].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : a[1] < b[1] ? -1 : 1));
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  const byTicker: Record<string, number> = {};
  for (const r of sorted) byTicker[r[1]] = (byTicker[r[1]] ?? 0) + 1;

  writeFileSync(OFAC_MODULE, renderOfacModule({ source: SOURCE, publish_date: publishDate, record_count: recordCount, addresses: sorted.length, by_ticker: byTicker, sha256 }, sorted));
  console.log(`OFAC SDN ${publishDate}: ${sorted.length} digital currency addresses from ${recordCount} records → ${OFAC_MODULE.pathname}`);
  console.log(JSON.stringify(byTicker));
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
